language: ruby
cache: bundler
rvm:
- 2.1.2
services:
- postgresql
env:
  matrix:
  - RAILS_ENV=test
  global:
  - secure: o3S7S1UTxOAly7OL2zsDgtAO/eJktCBvvdH6DwRaNn1BSYn/WkTcQ6wVAWCNEMPGipjqPdBOAACH4XrIyCeRYuwkZiQOoUp1ppkyqMEWQu4qS+U928rOEoENUv0FuBj1u6o8ghu14bMciJHw4uzIFHpA7DxPeFiOtev+cGjZHNQ=
  - secure: kI3la+UXvtu8OYHA98q1UG9BFvmyh+AfwYQkYoyuW021UJ5v+WaShaqK9X4tX1nIenEWLNa8SqIsXd8YC8ITiISXMYI/BkCp4uWiCq3AJCklxGu528XSPxDPYKtunV8J2Xa12mtNWoHuoS8bzfEossnw31/ipvW6Zfc9e1X/u3s=
  - secure: timSAMJPJHwoCm03rUvEz6M3oY2S7iyrrCt7FCzxywscCuTCw6PZHb1k5OXGVwVtaVH3nozTdZINKMaAeBMBHizSnVW55t8yfYWhCIOrQ4SUh0NPH4tR4hPEMkjw0ppbVzgV3w31Yv2dFESm0Cb07RdpW0JxWtYRMwHbmiYQSbc=
  - secure: PaxcWFlYBGT7TH9tU8JLQ08pRKxSV20ECxY/jPfqhbkQvDdpa16H/4XbzUOe+MGuHKaHuD4zPiOKL8jRULjF8VKposU6KjF7814fhudhAd7xXUzz9+uU4obxB3ORLqthDG1mPMB7NiuccXhKCsZ7dG2qQR5kqQQRA7oPQ3hrHO8=
  - secure: LzB7Ig3FNPs6wyifBrI5jDw0AiK7q5pNfmE9RuejqtLyZOsWDa4c53B0WKTKMypKOd06xQd7CoK8KYw5dKdFTLlGVNPWmrIqy2kp2W/XC05IHyh7p1+tBhdd89e3tDjGqhbKUZoyv4uz74p0x3l17IonBwMf+TxLCuR1KsY2YlA=
  - secure: JoYgPCZKJpvy4KTQk5uheohNqsj3niAlXcjxqBDbrWJ9aCkoWG7DeAUJibM3r/a7NbUC9YSz/cjm2I4II7Q1witW/vSaI8Cp0FwIyOL9jNb0A04P+9Yb9cVfZ2+fgTk/RH7NnJ/6TQUshkxwRUd+3AxSajk/kxHfNwNBfoUqqF4=
  - secure: Wxahbd9zfo919pGgdmoPKPJTTZO0Sg3TBDEfNOv0Dw80+HlKU5A0RpFtno/oZ6fExYLbfJ5pkVa2TOvdNj568pcDCCbvP80oagZflABfgtNH5jStOyONy/Iev4t1xRTdI5b8s2lnTISxflot2ED5LWwMf7/fzFcVnxAZ0vRy++I=
  - secure: CidoCHMqGay0F5cAJwfvelzhSigMG4p4pN1Y5P/TMG4h0YO9JxMHHFviNy1Icy2zkvcYcN4sG7DtZZBAfGQ/USU42ZQ38KPh3Yycl5BRocWsBvwrBigujB2I3fCK6jDE6zjfkaTWputrqjfazbVK6YSYKUhELKisiNkmAV1+lyw=
  - secure: DKM77m5g2MNDUEE+yTXPbv7A8Pt4UoiHkX9qtfwM7LgEC43abVyAsL6PAxonmyCp43LdPtFtm1dUSkrqDXN0LdDbc2wsDBWGDVbTKTEHS9pdzEOgVBU2PyKji5iTLkKeHUADE2p1+qoHtgdUq6c//KLeAp/7buj5atkKhV6Kh1E=
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- cp -f config/travis/database.yml config/database.yml
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:create db:schema:load
script:
- bundle exec rspec spec
after_success:
- git fetch --unshallow
notifications:
  email:
    recipients:
    - b.kosmowski@selleo.com
  hipchat:
    rooms:
    - '2fe7e1f5cdaf9e06957b9e0f287bb0@SAApp :: notifications'
deploy:
  provider: heroku
  api_key:
    secure: QctjDTu8mDbvUEF8v0Tpcu2KuVu8uXUHu0LgfoNWApVSw3z1NVwZOio+UuMXRf6pWNp939vlvN9EYqUdRBSzmyGtnLwh30Uevq73UhdHHk8Ov111eJTCJlC0C6gIoGRB5i3j1MQdXfLgLoJkj29AIudWI7oxJBN/sILY9yYS4/U=
  app: saapp-staging
  on:
    repo: Selleo/saapp
  run: rake db:migrate
  strategy: git
