language: ruby
cache: bundler
rvm:
- 2.1.0
services:
- postgresql
env:
  matrix:
  - RAILS_ENV=test
  global:
  - secure: FV4oLVJDk7ykG2sDl0eDqohLf6415GLhRxDsqm5ggS/bbUp4zJziEAH0nEuPWl4GAzg7usldE1piIkA6qlaz+lToeHVCOrSVr62v/TwdXsp6zXVelKgiBoosDEdwqqVCrPPcbCw7yWIpjoTtyNF1rJrPW6hcslYr0CJpcIfSiMA=
  - secure: EN8mVqGN4hpBo1XKnnmv3khyP43Y/M3kfVaJqCUuHprhxMRTj0mYBQnRJnHq9YYWwipIlpAy5KcJMo2bAM413okF6qcvOEni030h8K/QA2Cv2GGOWDDeDe9UjPr3851E+YJ2r8itOFUOwdInFe9a9EJanRKxQT6Xy/k4JrFqe78=
  - secure: kfrTi9k5ABLwZ3ilWGCh4rB82lq+mJjPt9EsLGzULrnfV/L0ZlIKPrHID0UJyapXL3wT3w4Lft6ImI0Ek781G1uVlNJzIOGGdCrdbTtURbvy/EQzQUbeBxtzyjvbjaLERF0zosqWwNqbjGEwmv7B6wbJ5fEsulz0XLRQwruObmo=
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
- cp -f config/travis/database.yml config/database.yml
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- bundle exec rake db:create db:schema:load
script:
- bundle exec rspec spec
after_success:
- git fetch --unshallow
notifications:
  email:
    recipients:
    - b.kosmowski@selleo.com
  hipchat:
    rooms:
    - '2fe7e1f5cdaf9e06957b9e0f287bb0@SAApp :: notifications'
deploy:
  provider: heroku
  api_key:
    secure: QctjDTu8mDbvUEF8v0Tpcu2KuVu8uXUHu0LgfoNWApVSw3z1NVwZOio+UuMXRf6pWNp939vlvN9EYqUdRBSzmyGtnLwh30Uevq73UhdHHk8Ov111eJTCJlC0C6gIoGRB5i3j1MQdXfLgLoJkj29AIudWI7oxJBN/sILY9yYS4/U=
  app: saapp-staging
  on:
    repo: Selleo/saapp
  run: 'rake db:migrate'
  strategy: git
