subject: TODO Reset password instructions
body: |
  <p>Hej *|email|*!</p>

  <p>Der er rekvireret et link til at ændre din adgangskode.Du kan ændre koden via nedenstående link.</p>

  <p><a href="*|edit_password_url|*">Ændre adgangskode</a></p>

  <p>Hvis du ikke selv rekvirerede dette link, kan du bare se bort fra denne email.</p>
  <p>Din adgangskode ændres ikke før du klikker linket ovenfor og vælger en ny kode.</p>
