subject: Confirmation instructions
body: |
  <p>Welcome *|email|*!</p>

  <p>You can confirm your account email through the link below:</p>

  <p><a href="*|confirmation_url|*">Confirm my account</a></p>
