subject: Unlock instructions
body: |
  <p>Hello *|email|*!</p>

  <p>Your account has been locked due to an excessive number of unsuccessful sign in attempts.</p>

  <p>Click the link below to unlock your account:</p>

  <p><a href="unlock_url">Unlock my account</a></p>
