subject: Welcome to BetterSalesman
body: |
  <p>Welcome *|display_name|*!</p>

  <p>Welcome in BetterSalesman!</p>

  <p>There will be a link here for you to download an app... soon ;)</p>

  <p>Here is your password</p>

  <p>*|password|*</p>
