subject: Welcome to BetterSalesman
body: |
  <p>Hi *|display_name|*!</p>

  <p>Welcome to BetterSalesman!</p>

  <p>There will be a link here for you to download an app... soon ;)</p>

  <p>Here is your password that you can change after your first login:</p>

  <p>*|password|*</p>
