subject: Welcome to BetterSalesman
body: |
  <p>Hi *|display_name|*!</p>

  <p>Welcome to BetterSalesman!</p>

  <p>*|message|*</p>

  <p>
  <a href="https://itunes.apple.com/us/app/bettersalesman/id911319758">https://itunes.apple.com/us/app/bettersalesman/id911319758</a>
  </p>

  <p>Here is your password that you can change after your first login:</p>

  <p>Username = *|email|*</p>

  <p>Password = *|password|*</p>
